
ppo:
  cold_hit_bonus: 0.3
  dual_guard_bonus: 0.15
core_pool:
  cold_boost_threshold: 0.04
  cold_boost_factor: 1.15
  entropy_top5_cap: 0.30
wheel:
  max_repeat: 2
  groups:
    high_risk: 6
    low_risk: 4
ga:
  de_generations: 300
  pso_generations: 200
  ga_crossover_rate: 0.2
