# v3.0 Configuration for Lotto 539 Predictor
data:
  raw_file: data/clean_539_3251.txt
  last_period: 114127
  dual_window:
    short: 300
    long: 1500
  short_hot_p: 8

model:
  neural_net:
    architecture: BiGRU_Attn
    epochs_warm_fit: 3

  reinforcement_learning:
    algo: PPO
    reward_mode: expected_prize_log_v3
    short_hot_bonus: 0.30
    mid_cold_bonus: 0.20
    dual_guard_bonus: 0.15
    epsilon_max: 0.40

  evolutionary:
    hit2_weight: 1.4
    expected_prize_weight: 0.6
    diversity_weight: 0.5
    midcold_weight: 0.3
    shorthot_weight: 0.2
    de_generations: 250
    ga_restart_patience: 30

elastic_k:
  mid_cold_min_ratio: 0.15
  sigma_force_k15: 0.02
  high_tail_min: 2
  guard: [3, 35, 38]

wheel:
  version: 2.6
  high_rule: "Guard + >=1 Hot + <=1 Cold + >=1 Mid"
  low_rule:  "Guard + >=1 Hot + 0 Cold"
  cold_max_global: 2

monte_carlo:
  samples: 150000
  hit3_threshold: 0.42

output:
  report_dir: output/reports
  package_dir: output/package