core_pool:
- 1
- 3
- 12
- 13
- 14
- 16
- 17
- 18
- 19
- 26
- 34
- 35
- 36
- 38
generated_at: '2025-05-23T16:24:47.704516'
guards:
- 3
- 34
- 35
- 38
version: v2.9
wheels:
  high:
  - - 3
    - 13
    - 16
    - 26
    - 34
  - - 1
    - 16
    - 18
    - 19
    - 38
  - - 3
    - 14
    - 16
    - 26
    - 34
  - - 13
    - 14
    - 16
    - 18
    - 35
  - - 3
    - 14
    - 16
    - 19
    - 34
  - - 13
    - 16
    - 17
    - 19
    - 35
  low:
  - - 13
    - 18
    - 34
    - 36
    - 38
  - - 3
    - 12
    - 18
    - 34
    - 38
  - - 1
    - 3
    - 13
    - 26
    - 35
  - - 3
    - 17
    - 18
    - 34
    - 38
