cold_boost:
  cold_min: 1.00
  cold_max: 1.20
  semi_min: 1.00
  semi_max: 1.10
ppo:
  cold_hit_bonus: 0.1
  dual_guard_bonus: 0.25
  segment_cover_high: 0.10
fitness:
  hit2_weight: 2.0
  cold_cover_weight: 1.1
elastic_k:
  high_tail_min: 2
  sigma_force_k14: 0.02
wheel:
  high_risk_rule: ">=1 Cold + Guard + Mid"
  low_risk_rule: "Guard + <=1 Hot"
